language: c

compiler:
  - gcc
  - clang

script: ./build.sh

after_success:
 - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get -qq install valgrind; fi
 - if [ "$TRAVIS_OS_NAME" = "linux" ]; then valgrind --leak-check=full --show-reachable=yes bin/reader_network64 -ionline; fi

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "klrX5K7+mDSa4Z9KHS4vhi9WaZ7ly2qwDq5VVs5d1rwGh1QGOKLhWorpECzeIif3++tT144lvIa/c/li6rAmB8N8A1JPI/nxwKg5AMX1FJLH8SSysAGzTK4p2KXZyq3f/ol6ZThKgqhYm3UL+126MYTggFEZYC4ZCId47jU7rLo="

addons:
  coverity_scan:
    project:
      name: "ifsnop/reader_network"
      description: "A package of utilities to record and work with multicast radar data in ASTERIX format. (radar as in air navigation surveillance)"
    notification_email: diego.torres@gmail.com
    build_command_prepend:
    build_command: ./build.sh
    branch_pattern: master
